[tool.poetry]
name = "nanogpt"
version = "0.1.0"
description = ""
authors = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.0.0"
numpy = "^1.24.3"
transformers = "^4.28.1"
datasets = "^2.12.0"
tiktoken = "^0.3.3"
wandb = "^0.15.0"
tqdm = "^4.65.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
